# =========================================================
# APPLICATION
# =========================================================

spring.application.name=Accounts


# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


# =========================================================
# SERVER
# =========================================================

server.port=8081


# =========================================================
# JWT SECURITY
# =========================================================

app.security.jwt-secret=${JWT_SECRET}
app.security.refresh-token-days=7


# =========================================================
# CORS
# =========================================================

app.security.allowed-origins=http://localhost:5173


# =========================================================
# OPENAI
# =========================================================

openai.api.key=${OPENAI_API_KEY}