spring.application.name=Accounts

# Database Configuration
spring.datasource.url=jdbc:sqlite:accounts.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA Configuration
spring.jpa.database-platform=com.vpm.Accounts.config.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

# Change default port to avoid conflicts
server.port=8081
